# AUTOGENERATED! DO NOT EDIT! File to edit: ../05_applications.ipynb.

# %% auto 0
__all__ = ['plot_vector', 'plot_bivector', 'plot_basis_blade']

# %% ../05_applications.ipynb 2
import matplotlib.pyplot as plt

from .basisblades import BasisBlade, ga2d
from .multivectors import Multivector, add
from .products import basis_blade_gp, gp

# %% ../05_applications.ipynb 6
def plot_vector(b: BasisBlade, ax: plt.Axes) -> plt.Axes:

    return ax

def plot_bivector(b: BasisBlade, ax: plt.Axes) -> plt.Axes:

    return ax

def plot_basis_blade(*args: tuple[BasisBlade]) -> plt.Figure:
    # Get components
    # Plot scalar, vector, or bivector
    return
